import { ImageLoaderConfig } from '@angular/common';

/** Widths generated by scripts/optimize-photos.mjs. Keep both in sync. */
export const PHOTO_WIDTHS = [480, 960, 1600];

/**
 * NgOptimizedImage loader for the optimised photos: `photos/benedict-trufa`
 * becomes `/photos/benedict-trufa-960.webp`, picking the smallest width that
 * covers the requested one. The path is absolute because the build keeps a
 * single photos/ folder at the root, shared by every locale. Other images
 * (logos) are returned unchanged.
 */
export function photoLoader({ src, width }: ImageLoaderConfig): string {
  if (!src.startsWith('photos/')) {
    return src;
  }
  const target = width ?? 960;
  const w = PHOTO_WIDTHS.find((candidate) => candidate >= target) ?? PHOTO_WIDTHS.at(-1);
  return `/${src}-${w}.webp`;
}
